#!/usr/bin/env bash
set -euo pipefail
ROOT="${1:-assets}"
echo "Downloading images into: $ROOT"
mkdir -p "${ROOT}/core/real_time_detection"
echo "-> core/real_time_detection/busy_intersection_unsplash.jpg"
curl -L "https://unsplash.com/photos/S___NBJSno0/download?force=true" -o "${ROOT}/core/real_time_detection/busy_intersection_unsplash.jpg"
mkdir -p "${ROOT}/core/instance_segmentation"
echo "-> core/instance_segmentation/supermarket_shelves_wikimedia.jpg"
curl -L "https://upload.wikimedia.org/wikipedia/commons/0/0f/Faced_products_on_a_supermarket_shelf.JPG" -o "${ROOT}/core/instance_segmentation/supermarket_shelves_wikimedia.jpg"
mkdir -p "${ROOT}/core/image_classification"
echo "-> core/image_classification/city_street_unsplash.jpg"
curl -L "https://unsplash.com/photos/IH3kVwdbisE/download?force=true" -o "${ROOT}/core/image_classification/city_street_unsplash.jpg"
mkdir -p "${ROOT}/core/pose_keypoint"
echo "-> core/pose_keypoint/overhead_crosswalk_unsplash.jpg"
curl -L "https://unsplash.com/photos/WVFQv92z_as/download?force=true" -o "${ROOT}/core/pose_keypoint/overhead_crosswalk_unsplash.jpg"
mkdir -p "${ROOT}/core/oriented_detection"
echo "-> core/oriented_detection/aerial_fields_wikimedia.jpg"
curl -L "https://upload.wikimedia.org/wikipedia/commons/8/80/120627-A-LE308-009.jpg" -o "${ROOT}/core/oriented_detection/aerial_fields_wikimedia.jpg"
mkdir -p "${ROOT}/video/mot_cctv"
echo "-> video/mot_cctv/night_crowd_unsplash.jpg"
curl -L "https://unsplash.com/photos/IxWQiQjSxsc/download?force=true" -o "${ROOT}/video/mot_cctv/night_crowd_unsplash.jpg"
mkdir -p "${ROOT}/video/people_counting"
echo "-> video/people_counting/overhead_crosswalk_unsplash_dup.jpg"
curl -L "https://unsplash.com/photos/WVFQv92z_as/download?force=true" -o "${ROOT}/video/people_counting/overhead_crosswalk_unsplash_dup.jpg"
mkdir -p "${ROOT}/video/zone_intrusion"
echo "-> video/zone_intrusion/lobby_escalator_unsplash.jpg"
curl -L "https://unsplash.com/photos/ARwq5tGGyvQ/download?force=true" -o "${ROOT}/video/zone_intrusion/lobby_escalator_unsplash.jpg"
mkdir -p "${ROOT}/video/ppe_action"
echo "-> video/ppe_action/helmet_worker_wikimedia.jpg"
curl -L "https://upload.wikimedia.org/wikipedia/commons/2/2d/Construction_Worker_-_Flickr_-_Saad.Akhtar.jpg" -o "${ROOT}/video/ppe_action/helmet_worker_wikimedia.jpg"
mkdir -p "${ROOT}/industry/autonomous_driving"
echo "-> industry/autonomous_driving/aerial_intersection_unsplash.jpg"
curl -L "https://unsplash.com/photos/acLp1oYUsUc/download?force=true" -o "${ROOT}/industry/autonomous_driving/aerial_intersection_unsplash.jpg"
mkdir -p "${ROOT}/industry/traffic_parking"
echo "-> industry/traffic_parking/parking_lot_wikimedia.jpg"
curl -L "https://upload.wikimedia.org/wikipedia/commons/f/f7/Aerial_view_of_an_empty_car_parking_lot.jpg" -o "${ROOT}/industry/traffic_parking/parking_lot_wikimedia.jpg"
mkdir -p "${ROOT}/industry/retail_shelves"
echo "-> industry/retail_shelves/grocery_shelves_wikimedia.jpg"
curl -L "https://upload.wikimedia.org/wikipedia/commons/0/0f/Faced_products_on_a_supermarket_shelf.JPG" -o "${ROOT}/industry/retail_shelves/grocery_shelves_wikimedia.jpg"
mkdir -p "${ROOT}/industry/manufacturing_qc"
echo "-> industry/manufacturing_qc/factory_line_unsplash.jpg"
curl -L "https://unsplash.com/photos/dVZaWyfE3UA/download?force=true" -o "${ROOT}/industry/manufacturing_qc/factory_line_unsplash.jpg"
mkdir -p "${ROOT}/industry/logistics_warehouse"
echo "-> industry/logistics_warehouse/warehouse_forklift_unsplash.jpg"
curl -L "https://unsplash.com/photos/82ZiY5pzl1c/download?force=true" -o "${ROOT}/industry/logistics_warehouse/warehouse_forklift_unsplash.jpg"
mkdir -p "${ROOT}/industry/construction_safety_violation"
echo "-> industry/construction_safety_violation/no_fall_protection_wikimedia.jpg"
curl -L "https://upload.wikimedia.org/wikipedia/commons/9/96/Construction_workers_not_wearing_fall_protection_equipment.jpg" -o "${ROOT}/industry/construction_safety_violation/no_fall_protection_wikimedia.jpg"
mkdir -p "${ROOT}/industry/security_surveillance"
echo "-> industry/security_surveillance/cctv_camera_unsplash.jpg"
curl -L "https://unsplash.com/photos/2E9BKrpMQaY/download?force=true" -o "${ROOT}/industry/security_surveillance/cctv_camera_unsplash.jpg"
mkdir -p "${ROOT}/industry/healthcare_polyp"
echo "-> industry/healthcare_polyp/endoscopic_polyp_wikimedia.jpg"
curl -L "https://upload.wikimedia.org/wikipedia/commons/f/fd/Polyp.jpeg" -o "${ROOT}/industry/healthcare_polyp/endoscopic_polyp_wikimedia.jpg"
mkdir -p "${ROOT}/industry/agriculture_drone"
echo "-> industry/agriculture_drone/drone_field_unsplash.jpg"
curl -L "https://unsplash.com/photos/y4kBr7-97gc/download?force=true" -o "${ROOT}/industry/agriculture_drone/drone_field_unsplash.jpg"
mkdir -p "${ROOT}/industry/wildlife_drone"
echo "-> industry/wildlife_drone/aerial_wildlife_unsplash.jpg"
curl -L "https://unsplash.com/photos/UCRu5bmzNVM/download?force=true" -o "${ROOT}/industry/wildlife_drone/aerial_wildlife_unsplash.jpg"
mkdir -p "${ROOT}/industry/sports_analytics"
echo "-> industry/sports_analytics/soccer_match_wikimedia.jpg"
curl -L "https://upload.wikimedia.org/wikipedia/commons/2/24/Football_match_at_Wincham_Park_Stadium_%28geograph_4383139%29.jpg" -o "${ROOT}/industry/sports_analytics/soccer_match_wikimedia.jpg"
mkdir -p "${ROOT}/industry/document_barcode"
echo "-> industry/document_barcode/scanning_barcode_wikimedia.jpg"
curl -L "https://upload.wikimedia.org/wikipedia/commons/5/57/The_scanning_the_barcode_on_the_box.jpg" -o "${ROOT}/industry/document_barcode/scanning_barcode_wikimedia.jpg"
mkdir -p "${ROOT}/industry/license_plate"
echo "-> industry/license_plate/diplomatic_plate_wikimedia.jpg"
curl -L "https://upload.wikimedia.org/wikipedia/commons/5/56/CD_diplomatic_license_plate_on_a_car_%28cropped%29.jpg" -o "${ROOT}/industry/license_plate/diplomatic_plate_wikimedia.jpg"
mkdir -p "${ROOT}/industry/fire_smoke"
echo "-> industry/fire_smoke/wildfire_smoke_wikimedia.jpg"
curl -L "https://upload.wikimedia.org/wikipedia/commons/7/76/Wildfire_Smoke_-_52958907889.jpg" -o "${ROOT}/industry/fire_smoke/wildfire_smoke_wikimedia.jpg"
mkdir -p "${ROOT}/industry/face_masks"
echo "-> industry/face_masks/people_with_masks_wikimedia.jpg"
curl -L "https://upload.wikimedia.org/wikipedia/commons/c/c8/Bucuresti%2C_Romania._Metrou._Persoane_foarte_responsabile._Poarta_masti_reglementar._August_2020._%282%29.jpg" -o "${ROOT}/industry/face_masks/people_with_masks_wikimedia.jpg"